name: Build
on: push

jobs:
  build-internal:
    timeout-minutes: 5
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            ubuntu-20.04-gcc-7,
            ubuntu-20.04-gcc-8,
            ubuntu-20.04-gcc-9,
            ubuntu-20.04-gcc-10,
            ubuntu-20.04-clang-6.0,
            ubuntu-20.04-clang-7,
            ubuntu-20.04-clang-8,
            ubuntu-20.04-clang-9,
            ubuntu-20.04-clang-10,
            macOS-10.14-xcode-10.3,
            macOS-10.14-gcc-9,
        ]
        include:
          - name: ubuntu-20.04-gcc-7
            os: ubuntu-20.04
            compiler: gcc
            version: "7"

          - name: ubuntu-20.04-gcc-8
            os: ubuntu-20.04
            compiler: gcc
            version: "8"

          - name: ubuntu-20.04-gcc-9
            os: ubuntu-20.04
            compiler: gcc
            version: "9"

          - name: ubuntu-20.04-gcc-10
            os: ubuntu-20.04
            compiler: gcc
            version: "10"

          - name: ubuntu-20.04-clang-6.0
            os: ubuntu-20.04
            compiler: clang
            version: "6.0"

          - name: ubuntu-20.04-clang-7
            os: ubuntu-20.04
            compiler: clang
            version: "7"

          - name: ubuntu-20.04-clang-8
            os: ubuntu-20.04
            compiler: clang
            version: "8"

          - name: ubuntu-20.04-clang-9
            os: ubuntu-20.04
            compiler: clang
            version: "9"

          - name: ubuntu-20.04-clang-10
            os: ubuntu-20.04
            compiler: clang
            version: "10"

          - name: macOS-10.14-xcode-10.3
            os: macOS-10.14
            compiler: xcode
            version: "10.3"

          - name: macOS-10.14-gcc-9
            os: macOS-10.14
            compiler: gcc
            version: "9"
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install Compiler (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get install -y g++-${{ matrix.version }}
            echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
          else
            sudo apt-get install -y clang-${{ matrix.version }}
            echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
          fi
      - name: Install and Test (Linux)
        if: runner.os == 'Linux'
        # Sudo is required for Ubuntu 18.04 on GitHub.
        # Otherwise "mkdir -p build/Testing/Temporary" fails with
        # "mkdir: cannot create directory ‘build/Testing’: Permission denied"
        # (mkdir itself was a test after "ctest" failed to create the directory)
        run: (sudo ./install-linux.sh && sudo make tests)
      - name: Install Compiler (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install cmake ninja
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            brew install gcc@${{ matrix.version }}
            echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
          else
            sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          fi
      - name: Install and Test (macOS)
        if: runner.os == 'macOS'
        run: (./install-mac.sh && make tests)

  build-external:
    timeout-minutes: 5
    name: Build External
    runs-on: ubuntu-20.04
    container:
      image: ${{ matrix.container }}
      options: --user root
    strategy:
      matrix:
        name: [
            debian-stable-gcc-7,
            debian-stable-gcc-8,
            debian-stable-clang-7,
        ]
        include:
          - name: debian-stable-gcc-7
            container: debian:stable
            compiler: gcc
            version: "7"

          - name: debian-stable-gcc-8
            container: debian:stable
            compiler: gcc
            version: "8"

          - name: debian-stable-clang-7
            container: debian:stable
            compiler: clang
            version: "7"

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install Compiler
        run: |
          apt-get update
          apt-get install -y sudo   # sudo is not present on the image
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            apt-get install -y g++-${{ matrix.version }}
            echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
          else
            apt-get install -y clang-${{ matrix.version }}
            echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
          fi
      - name: Install and Test
        run: (./install-linux.sh && make tests)
